import React, { Component } from 'react';
import './ControlPanel.css';
import Button from 'react-bootstrap/Button';
import ButtonGroup from 'react-bootstrap/ButtonGroup';

class ControlPanel extends Component {
	state = {}
	
	render() {
		return(
			<>
				<h1>Control Panel</h1>
				<p>Role: Creator</p>
				<div>
					<label>
						Enabled Viewer Password 
						<input onClick={this.setPasswordStatus} type="checkbox" />
					</label>
				</div>
				<p class="password">Autogenerated Password: 1234</p>
				<ButtonGroup vertical>
					<Button variant="primary" onClick={this.viewAsViewer}>View as Viewer</Button>{' '}
					<Button variant="primary" onClick={this.viewSnippet}>View another Snippet</Button>{' '}
					<Button variant="primary" onClick={this.createSnippet}>Create another Snippet</Button>{' '}
					<Button variant="primary" onClick={this.deleteSnippet}>Delete Snippet</Button>{' '}
				</ButtonGroup>
			</>
		)
	}
	
	setPasswordStatus() {
		console.log("changed password status");
	}
	
	
	viewAsViewer() {
		console.log("view as viewer");
	}
	
	viewSnippet() {
		console.log("view snippet");
	}
	
	createSnippet() {
		console.log("created snippet");
	}
	
	deleteSnippet() {
		console.log("deleted snippet");
	}
}

export default ControlPanel;