import React, { Component } from 'react';
import './ControlPanel.css';
import Button from 'react-bootstrap/Button';
import ButtonGroup from 'react-bootstrap/ButtonGroup';

import * as urls from '../api.js';

class ViewerControlPanel extends Component {
	state = {}
	
	render() {
		return(
			<>
				<h1>Control Panel</h1>
				<p>Role: Viewer</p>
				<p class="password">Autogenerated Password: 1234</p>
				<ButtonGroup vertical>
					<Button variant="primary" onClick={this.viewSnippet}>View another Snippet</Button>{' '}
					<Button variant="primary" onClick={this.createSnippet}>Create another Snippet</Button>{' '}
				</ButtonGroup>
			</>
		)
	}
	
	setPasswordStatus() {
		console.log("changed password status");
	}
	
	
	viewAsViewer() {
		console.log("view as viewer");
	}
	
	viewSnippet() {
		console.log("view snippet");
	}
	
	createSnippet() {
	    const base_url = "https://e061bpd3ph.execute-api.us-east-2.amazonaws.com/beta/";
	    const create_snippet_url = base_url + "new_snippet";    // POST
	    console.log(create_snippet_url);
	    var xhr = new XMLHttpRequest();
	    xhr.open("POST", create_snippet_url, true);
	
	    var sender = JSON.stringify();
	    xhr.send(sender);
	    
	    // Process the results and update the HTML as appropriate.
	    xhr.onloadend = function() {
	      console.log(xhr);
	      console.log(xhr.request);
	      if (xhr.readyState === XMLHttpRequest.DONE) {
	        if (xhr.status === 201) {
	          console.log ("XHR: " + xhr.responseText);
	          var js = JSON.parse(xhr.responseText);
	          var snippetID = js["snippetId"];
	          console.log ("Created a new snippet: " + snippetID);
	        } else {
	          console.log("actual: " + xhr.responseText);
	          var js = JSON.parse(xhr.responseText);
	          var err = js["response"];
	          alert (err);
	        }
	      }
	    }
		
	    console.log("created snippet");
	}
	
	deleteSnippet() {
		console.log("deleted snippet");
	}
}

export default ViewerControlPanel;
